image: node:latest
services:
  - mongo:latest
  - redis:latest

variables:
  MONGODB_DB_HOST: mongo
  REDIS_HOST: redis
  TELEGRAM_TOKEN: test
  TELEGRAM_URL: lol
  NODE_ENV: test

npm_run:
  script:
    - npm install -s
    - npm test
